name: Clang Format Auto Fix

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format and auto-fix
        run: |
          find Source -type f \( -name "*.cpp" -o -name "*.h" \) -exec clang-format -i {} \;

      - name: Commit and push changes if needed
        run: |
          git add Source
          if git diff --cached --quiet; then
            echo "✅ No formatting changes needed."
          else
            git commit -m "chore(format): auto-fix with clang-format"
            git push
            echo "✅ Pushed auto-format changes to main."
          fi